import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import PopupManager from "@/lib/PopupManager";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`antialiased max-w-150 mx-auto box-border p-0 m-0`}
         >
            <PopupManager>
               <div className="h-screen flex flex-col mx-5 box-border pb-5 min-h-0">
                  <Link href="/" className="px-5 py-1 block font-bold italic text-sm">HParty2</Link>
                  <div className="flex-1 flex flex-col min-h-0">
                     {children}
                  </div>
               </div>
            </PopupManager>
         </body>
      </html >
   );
}
